### ISSUE TITLE
Dependent Care mirrored in Distribution Phase

### ISSUE THREAD

**Issue by pdesmaratt** [llblumer/Retireator#10]
On the Expenses tab when you put in a value for dependent care for the accumulation phase it gets mirrored in the distribution phase. Is this just for convenience? I would think if you have dependents during the accumulation phase that those dependents would have moved on to take care of themselves by the distribution phase. For now I am zero'ing out this value.

**Comment by llblumer** [comment]
Yeah the Dependent care triggering isn't very good.

**Comment by llblumer** [comment]
All the expense defaults are handled in a consistent way, I'd rather not diverge off that one row.  You can override it very easily.
