### ISSUE TITLE
I'm confused about what the Household Savings chart is telling me. 

### ISSUE THREAD

**Issue by pdesmaratt** [llblumer/Retireator#11]
I see that it goes all the way up to my life expectancy age but  I'm not sure what exactly this chart is telling me. How is the after tax money more then the before tax money. Seems backwards. No debt is listed which i'm guessing is a good thing.

**Comment by llblumer** [comment]
After tax money is your core account and any Roth accounts (which has been taxed already).  Before tax is 401K's and IRA's.

**Comment by pdesmaratt** [comment]
Ok got it. Thanks for the explanation I get it now.
