### ISSUE TITLE
Need a setting to reset a tab and not the entire spreadsheet. 

### ISSUE THREAD

**Issue by pdesmaratt** [llblumer/Retireator#12]
I think I may have messed up my income page. I mistakenly did a cell copy and copied my employer income from 2015 to 2020. Now my income page is jacked. I don't want to redo everything I just want to restart the Income tab. Is this possible?

**Comment by llblumer** [comment]
You should be able to just delete the values, and the defaults will repair themselves.

In the future, use Excel "paste values" to paste.  Don't just paste.

**Comment by pdesmaratt** [comment]
Ok but its hard to tell if you have messed up the sheet with a cell copy/paste. In that case your not sure which cells to delete the values in especially if there is etrapolation going on. There should be a menu item like 'Wipe' instead it should be 'Wipe current tab'.

**Comment by llblumer** [comment]
If you really get it jacked up you can re-import.  Pull down a clean Retireator, then "Import" the values from the previous workbook from the Setup page.  That's a good technique to master anyway for staying up-to-date.

**Comment by pdesmaratt** [comment]
ok I'm just going to start over it doesn't take that long to input the values again.

**Comment by llblumer** [comment]
So you can "trim" data as well.  Re-run setup, deselect "Employer income" or anything else, then hit OK, then re-run setup again, and re-enable as desired.  All setup parameters related to those features will be reset to blanks or defaults.  I don't plan to implement a sheet wipe as it is a bit arbitrary.
