### ISSUE TITLE
Google Sheets support

### ISSUE THREAD

**Issue by pdesmaratt** [llblumer/Retireator#13]
1 - Tried pulling the spreadsheet into google sheets which is googles online version of excel. The spreadsheet doesn't work. Just fyi. 

https://docs.google.com/spreadsheets

![google_sheets_2](https://cloud.githubusercontent.com/assets/11318778/11165094/41cd8008-8ad3-11e5-888b-49d2257c22ca.jpg)
![google_sheets_1](https://cloud.githubusercontent.com/assets/11318778/11165095/41da07ec-8ad3-11e5-9963-946ea254f651.jpg)

**Comment by llblumer** [comment]
Yeah that doesn't look very promising. 

I do a lot of work to keep Excel Online supported.  I just tested that and it looks ok.  You have to do the following though:

1) Complete Setup process and save
2) Re-open with macros disabled, disable Workbook protection, then save again

Then it can be uploaded to Excel Online.  Step 2 is kind of a pain so I need to think about that.
