### ISSUE TITLE
Set Retirement Age on setup page.

### ISSUE THREAD

**Issue by pdesmaratt** [llblumer/Retireator#17]
This is what confused me about the retirement date on the dashboard. 

Because I wasn't able to set the retirement date on the setup page I assumed that (going in with the idea that i would get my date from retireator that I shouldn't be setting a date for retirement. Retireator should tell me the date. 

With that though process I would see my income tabulated all the way until my life expectancy date.

Another issue that I see is there are two places that show the retirement date. "Retirement Date" the second cell with a value on the main page that I'm assuming is calculated from my life expectancy date and the second showing up in the dashboard which is empty (the value I assumed I couldn't edit but I do see now that it shows up in green". 

One way to resolve the confusion would be to simply add the "Retirement Date" to the setup page. 

That way you can avoid calculating income all the way until your life expectancy date. Without this the income to your death age will seem a bit strange until someone figures out that they have to either fill the entire form and run a simulation or simply enter a retirement age in the dashboard.

**Comment by pdesmaratt** [comment]
Now I'm confused because no matter what age I put in the dashboard it tells me a retirement date after I enter my information and press retireate.

**Comment by llblumer** [comment]
Press enter key to submit retirement date in Dashboard

**Comment by llblumer** [comment]
The 1210 release enforces a modal entry mode on Dashboard to prevent clicking off and leaving data entry in limbo.
