### ISSUE TITLE
Jumping to another sheet when entering Current Employer Income is a bit weird.

### ISSUE THREAD

**Issue by pdesmaratt** [llblumer/Retireator#18]
I get that your jumping to the current date on another sheet to enter the employment income but that could be confusing to some people. I would suggest letting someone enter the employment income on the same page and make your calculations behind the scene (if that is even possible) without switching to the income tab.

**Comment by llblumer** [comment]
Earlier versions worked like that, and it created documentation conundrums:
- You don't go to "Income" to enter your current income, you go to "Main"
- You can enter past and future income in Income, but not present income?

So I don't want to go back to that.  Closing issue.
