### ISSUE TITLE
Social Security Retirement Insurance Benefits checkbox seems confusing.

### ISSUE THREAD

**Issue by pdesmaratt** [llblumer/Retireator#4]
I don't see a need for this check box. No matter what age you stop working you will receive social security payments if you reach retirement age. So why have a checkbox for this?

**Comment by llblumer** [comment]
That's actually not true, you won't get SSRIB benefits until you apply for them.  Also some people don't have enough work credits or are otherwise exempt from SS.  So they won't want it shown.  But most people will want it enabled.  But all those options default off.  I might change that.

**Comment by pdesmaratt** [comment]
I would set the default value as checked.

**Comment by llblumer** [comment]
I think I prefer for Setup to come up as a blank slate.
