### ISSUE TITLE
Defined Benefit Percentage jumps to 100's of percent

### ISSUE THREAD

**Issue by pdesmaratt** [llblumer/Retireator#6]
I entered a 6 in the defined benefit percentage field and initially it jumped to 600%. I cleared the field out and put 6 in again and it chagned to 6.00%. 

Can't repro this but I haven't tried starting over. I'll try this again once I finish this pass.

**Comment by llblumer** [comment]
Thanks, I'm aware of this.  It's an Excel oddity when dealing with percentages.  I don't know if it is fixable.

**Comment by llblumer** [comment]
So, it's user error.  When you first enter a value in a percentage field, Excel adds the % character at the end for you.  If you leave it in place, you will get the expected "friendly" percentage.  If you blow away the % character somehow, Excel then treats it as a raw percentage from 0 - 1.

**Comment by pdesmaratt** [comment]
I didn't blow away the % character. I typed 6 then enter.
