### ISSUE TITLE
Value not valid error for Primary Benefits Filing Age

### ISSUE THREAD

**Issue by pdesmaratt** [llblumer/Retireator#7]
1 - I know 58 is an invalid value but this looks like an error but I'm not sure. If your going to spawn pop up message then I would be consistent with the means of telling the user that they entered an invalid value in the field. In the setup page the field turned red. I think that is more user friendly. This pop up message looks like the a software failure not user error.

![value_not_valid](https://cloud.githubusercontent.com/assets/11318778/11164765/bc1f12f6-8ac7-11e5-8bfd-b858fd86125a.jpg)

**Comment by llblumer** [comment]
Data validation rules don't have any verbage yet.  The minimum age for that is 62.  That is the expected result until I dress it up.
