### ISSUE TITLE
Employer Income past the set retirement age should not be shown or calculated

### ISSUE THREAD

**Issue by pdesmaratt** [llblumer/Retireator#8]
On the income tab when I enter my 2015 Employer Income and Passive Income the salary is extrapolated forward all the way to the age of 90. I don't see a need for displaying more values which makes this page more intimidating. On the main page I set what my planned retirement year will be. So the extrapolation at lease for Employer income should stop on the planned retirement year.

**Comment by llblumer** [comment]
Employer income and self employment income DO extrapolate to your retirement date, then zero out.  I'm not sure what you are seeing.  Passive income extrapolates until you die, which defaults to 92.

**Comment by pdesmaratt** [comment]
This is not what I saw. Employer income extrapolated all the way until my life expectancy ending of 90 years of age.

**Comment by llblumer** [comment]
Check it again.  By default, your retirement date is never (technically the year after you die).  Pull it in or Retireate it and then check the Income sheet again.  Works for me.

**Comment by pdesmaratt** [comment]
My retirement date was set to 67 when I saw this issue. My life expectancy was 90 years. I can redo the spreadsheet and try this again but I didn't have a retirement date after my life expectancy.

**Comment by llblumer** [comment]
So I'm guessing this is a side effect of the copy and paste debacle.  Paste values instead!

**Comment by pdesmaratt** [comment]
I have confirmed that this is NOT do to copy and paste. Also the first time it happened I had not yet copied and pasted the cell. But I was able to reproduce this again.

**Comment by llblumer** [comment]
Can you create a new simulation with dummy data that reproduces this and attach it?
