### ISSUE TITLE
No field for Mortgage in the Expenses tab

### ISSUE THREAD

**Issue by pdesmaratt** [llblumer/Retireator#9]
You mention that I should enter data for my mortgage but there is no field for this. I could put the mortgage in the rent field or put it in Miscellaneous 1 but I think mortgage is a pretty big expense that should have its own dedicated field. 

Not to mention paying mortgage is much different then any other expense because your paying into property you own so your not essentially burning that money its re-investing so mortgage should be handled differently then rent or miscellaneous.

**Comment by pdesmaratt** [comment]
***I'm not a renter. Never have rented never will rent. No support for people like me for mortgage in the expenses tab.

**Comment by llblumer** [comment]
You missed an important feature here.  Rerun setup (Add-Ins/Retireator/Setup), then select Home/Mortgate, then OK.  The Expenses tab will then display a powerful mortgage calculator too, and a Amortizer sheet will appear which displays the amortization table.

**Comment by pdesmaratt** [comment]
I would add some sort of message or notification or something in the expenses tab if Home/Mortgage is not enabled stating that if the user wants to include a mortgage they can turn on the setting. 

Why not have this enabled by default? A large percentage of people don't rent.
